apiVersion: v1
kind: Pod
metadata:
  name: stress
  namespace: roboshop
spec:
  containers:
  - name: stress
    image: jareddy1992/stress:v2
    imagePullPolicy: Always
    command: ["sleep","200"]

