apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
  - name: stress
    image: jareddy1992/stress
    command: ["sleep","200"]
    resources: 
     requests:
      cpu: "150m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "300mi"
      