apiVersion: v1
kind: Pod
metadata:
  name: stress
  namespace: roboshop
spec:
  containers:
  - name: stress
    image: jareddy1992/stress:v2
    command: ["sleep","200"]
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "300Mi"
        cpu: "500m"
